# Generated by Django 2.1.5 on 2019-02-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='ApellidoMaterno',
            new_name='Primer_Apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='ApellidoPaterno',
            new_name='Segundo_Apellido',
        ),
    ]
